version: '3.7'
services:
  api:
    container_name: atividade-final
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229
    env_file:
      - .env
    networks:
      - docker-network
    depends_on:
      - postgres
  postgres:
    container_name: db_atividade-final
    image: 'postgres:9.6.1'
    networks:
      - docker-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DB}
    volumes:
      - api_db_data:/var/lib/postgresql/data
networks:
  docker-network:
volumes:
  api_db_data:
